Cleaned up all interfaces and displays.
directus/next pull request #220
Opened 2020-09-08 17:06 UTC by Nitwel

2020-09-08 17:30 UTC, rijkvanzanten commented
Can you resolve the merge conflict @Nitwel?

2020-09-08 17:32 UTC, Nitwel commented
Sure!

2020-09-09 15:29 UTC, rijkvanzanten requested changes
I think we should make placeholders full width in all options. @benhaynes thoughts?

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/code/code.vue
> +			}
The template can be non-JSON types as well.

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/code/code.vue
> +
I believe there's a separate code mirror styles file

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/code/index.ts
> +	recommendedDisplays: ['raw'],
Raw display is forced recommended for every display. Can be omitted here

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/color/index.ts
> +	recommendedDisplays: ['color-dot'],
I don't know how I feel about having color-dot support both a "dynamic value" (eg when value = `published`, show blue) _and_ have it support a hex value to render 🤔 

I know the output is virtually identical (a colored dot), but the value it (re)presents is very different.. Thoughts @benhaynes?

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/display-template/index.ts
> +	],
The display template interface doesn't have a `collection` option

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/divider/divider.vue
> +		:inlineTitle="inlineTitle"
Use html-attr style:

```suggestion
		:inline-title="inlineTitle"
```

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/divider/index.ts
> +	recommendedDisplays: ['raw'],
Raw is always recommended

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/divider/index.ts
> +	recommendedDisplays: ['raw'],
Also, displays aren't visible for presentation fields I don't think 🤔 (shouldn't be at least)

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/markdown/index.ts
> +	recommendedDisplays: ['raw'],
raw is always recommended

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/notice/index.ts
> +	recommendedDisplays: ['raw'],
raw is always recommeded

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/radio-buttons/index.ts
> -			},
Lets leave this in so it's immediately clear what the default value is when setting up the options

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/radio-buttons/index.ts
> -			},
Lets leave this in so it's immediately clear what the default value is when setting up the options

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/repeater/index.ts
> +	recommendedDisplays: ['related-values'],
Does the repeater (non-relational JSON) interface work with the related values display? I don't think it does

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/repeater/options.vue
> +			</div>
We should discuss if and how we want to tackle this in the API / validation / permissions / etc. Seeing this is just a JSON blob, I don't think the API can / should do any validation for this. (@benhaynes)

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
A placeholder is not the same as the text that goes in the create-new-item button 🤔 

The placeholder would be the text that shows in the rows when they're empty IMO

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/repeater/options.vue
>  }
Would be nice if we could make this re-usable somehow 🤔 

Maybe worth making this a mixin, seeing there's multiple places where we want to/have to mimic the form without using `v-form`

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/slider/index.ts
> +	recommendedDisplays: ['rating'],
Not sure if rating is a good match for the `slider` interface 🤔 @benhaynes thoughts?

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/slug/index.ts
> +	recommendedDisplays: ['formatted-value'],
Formatted value is recommended for every interface

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/slug/index.ts
> +		},
Lets make this one full width

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/slug/index.ts
> +		{
That way it's 

```
[ Placeholder                                   ]
[ Icon (Left)        ]   [ Icon (Right)         ]
```

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/tags/tags.vue
> +			default: () => [],
We should expect the default value to be `null`. That's what it would be coming from the API as well

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/text-input/index.ts
> +	recommendedDisplays: ['raw'],
raw is always recommended

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/text-input/index.ts
> +			field: 'mask',
I believe the prop is called `masked` in the text-input interface

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/text-input/index.ts
> +			field: 'mask',
```suggestion
			field: 'masked',
```

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/textarea/index.ts
> +	recommendedDisplays: ['raw'],
raw is always recommended

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/user/user.vue
> +			type: [String, Object],
The user interface will never get an Object for it's value

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/wysiwyg/index.ts
> +	recommendedDisplays: ['formatted-value'],
formatted value is always recommended

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/interfaces/wysiwyg/index.ts
> +					closeOnContentClick: false,
This shouldn't be an interface option. It should be disabled by default in the dropdown multiselect interface

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/display.vue
> +			return recommendedItems;
What do these changes do?

Doesn't make it easier to read imo

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/interface.vue
> +				recommendedItems.push({ divider: true });
Not sure if this is any easier to read that what was there before

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +				/>
textarea is bigger than other interfaces, we'll have to double check how that jumps on the page when switching between types. Maybe we'll have to make the default value full width 
at all times (@benhaynes )

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +				/>
Should we use the datetime interface here?

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +		const default_value = computed({
camelCase

```suggestion
		const defaultValue = computed({
```

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +		const default_type = computed(() => {
What is this? What does it do?

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +		const default_type = computed(() => {
Oh, it's the scoped type you're using for the default value if statement above. I would change that to be inline honestly:

Before:

```
v-else-if="default_type === 'number'"
```

After:

```
v-else-if="['bigInteger', 'integer', 'float', 'decimal'].includes(state.fieldData.type)"
```

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +			default_type,
camelCase

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/store.ts
> +						state.fieldData.schema.is_nullable = false;
Lets also enforce the default value to be set if you explicitly set `is_nullable` to false

2020-09-09 15:29 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
>  				state.fieldData.meta.special = 'uuid';
Lets remove this from here as well in favor of doing all this in the store.ts file

2020-09-09 15:31 UTC, benhaynes commented
Yes, certain options should always be full-width... and `placeholder` is one of them.

2020-09-09 15:39 UTC, benhaynes commented on app/src/interfaces/color/index.ts
> +	recommendedDisplays: ['color-dot'],
Hmm, interesting. 

* **Color Dot** based on hex value (eg: color interface)
* **Color Dot** based on dynamic value (eg: category/status)
* **Label** based on dynamic value (eg: category/status)

I would say that we could either combine Color Dot and Label (making a "Show as Dot" option like in v8, or we need to rename these to be clearer (eg: `Label Dot` and `Color`).

2020-09-09 15:40 UTC, rijkvanzanten commented on app/src/interfaces/color/index.ts
> +	recommendedDisplays: ['color-dot'],
> making a "Show as Dot" option

My vote goes to this ☝️

2020-09-09 15:41 UTC, benhaynes commented on app/src/interfaces/repeater/options.vue
> +			</div>
Very useful/powerful feature(s) to have... and it makes sense to set them up in the interface options. That said, I agree that these should (ideally) be enforced by the API too. We've been trying to think of a way to make all of these validation rules global per field... that seems like the cleanest way forward.

The only exception is if the interface validation is really APP ONLY... can't think of any examples of that though.

2020-09-09 15:42 UTC, benhaynes commented on app/src/interfaces/slider/index.ts
> +	recommendedDisplays: ['rating'],
Hmm, I think it's a good option, but not recommended.

2020-09-09 15:47 UTC, rijkvanzanten commented on app/src/interfaces/repeater/options.vue
> +			</div>
Lets remove the "max_amount" option from the repeater options for the time being, until we figure out how to tackle this "for real" on the field level (w/ API support)

2020-09-09 15:50 UTC, benhaynes commented on app/src/interfaces/color/index.ts
> +	recommendedDisplays: ['color-dot'],
Agree — v8 for the win! We don't have conditional fields, but it SHOULD be clear that "Foreground Color" won't be used in "Dot Mode". I think this new structure makes sense given that we're converting this to be called `Label` now too.

2020-09-09 16:39 UTC, Nitwel commented on app/src/interfaces/display-template/index.ts
> +	],
collectionField prop of the interface should be it. But what exactly means `collectionField` / what does the prop want to get?

2020-09-09 16:40 UTC, Nitwel commented on app/src/interfaces/divider/index.ts
> +	recommendedDisplays: ['raw'],
As far as I remember they are.

2020-09-09 16:43 UTC, Nitwel commented on app/src/interfaces/repeater/index.ts
> +	recommendedDisplays: ['related-values'],
Ah yes that was my bad. I thought relational would also support json format! I guess we currently have no proper way of displaying json?

2020-09-09 16:50 UTC, Nitwel commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
Well, it is a placeholder. It is the text of the placeholder for a new Item. And for `createItemText`, it is not very obvious what it does. (You could understand it as a option to create text for an item)
So placeholder is the way to go IMO.

2020-09-09 16:51 UTC, Nitwel commented on app/src/interfaces/repeater/options.vue
>  }
💯 I just don't know how to that cause v-form is very complex aready.

2020-09-09 17:05 UTC, Nitwel commented on app/src/modules/settings/routes/data-model/field-detail/components/interface.vue
> +				recommendedItems.push({ divider: true });
I changed it so the order always stays the same only the divider does not get rendered when below 5 elements.
The reason for this is that it's disorientating when the recomended interface comes last.

2020-09-09 17:07 UTC, rijkvanzanten commented on app/src/interfaces/display-template/index.ts
> +	],
It requires a field name (string) of which the value is the collection

2020-09-09 17:09 UTC, rijkvanzanten commented on app/src/interfaces/repeater/index.ts
> +	recommendedDisplays: ['related-values'],
Not really 🤔 Feel free to start a discussion if you have any thoughts about what a good display for JSON would be

2020-09-09 17:10 UTC, rijkvanzanten commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
> It is the text of the placeholder for a new Item.

.. except it's not 😄 

![CleanShot 2020-09-09 at 13 09 38](https://user-images.githubusercontent.com/9141017/92630379-bfcea680-f29d-11ea-8e07-4460abd80512.png)

(1) = placeholder
(2) = create item text

2020-09-09 17:11 UTC, Nitwel commented on app/src/interfaces/display-template/index.ts
> +	],
Shouldn't we rename the prop to collectionName or to collection then cause collectionField is confusable with a field of the collection. (Thats what confused me)

2020-09-09 17:15 UTC, Nitwel commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
I still think it's quite confusing. 🤷‍♂️

2020-09-09 17:17 UTC, rijkvanzanten commented on app/src/interfaces/display-template/index.ts
> +	],
> Shouldn't we rename the prop to collectionName or to collection

No, cause the value isn't the name of a collection, the value is the name of another field on the page that in turn holds the collection name. So:

```
collection_name
[ text-input                               ]


template
[ display-template                         ]


Options:
template.collectionField = collection_name
```

2020-09-09 17:20 UTC, Nitwel commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +				/>
Sounds good. How is the interface vue-component called internally?

2020-09-09 17:25 UTC, rijkvanzanten commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
Sure, but renaming it `placeholder` is not the solution, as `placeholder` is something else in this context. We can workshop names though, would `ctaText` be better? `ctaText`, `createLabel`, `addLabel`, ?

2020-09-09 17:28 UTC, Nitwel commented on app/src/modules/settings/routes/data-model/field-detail/store.ts
> +						state.fieldData.schema.is_nullable = false;
Any ideas how to do this. Is there a required option? I currently only can think of letting the user not go to the next section.

2020-09-09 17:32 UTC, Nitwel commented on app/src/interfaces/repeater/repeater.vue
> +		placeholder: {
I really like addLabel but in the end it's up to you!

2020-09-09 17:37 UTC, Nitwel commented on app/src/interfaces/display-template/index.ts
> +	],
>It requires a field name (string) of which the value is the collection
Read that wrong.

2020-09-09 17:47 UTC, Nitwel commented on app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
> +				/>
I think you overlooked line 43. 😉 
![grafik](https://user-images.githubusercontent.com/22577866/92634925-4c488b80-f2d5-11ea-948d-69199a11aa68.png)

2020-09-09 17:55 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/store.ts
> +						state.fieldData.schema.is_nullable = false;
We could just set 

```ts
state.fieldData.schema.default_value = false;
```

whenever you change to a boolean type! That way we at least know for sure that a default value is set, and therefore `nullable` is met

2020-09-09 17:57 UTC, rijkvanzanten commented on app/src/interfaces/code/code.vue
> +			}
Don't hate me for this, but:

JSON is also valid JS, but we don't want to send a JSON object to the API when JavaScript is used as the language. We should check for props.type and only try JSON.parse when props.type == json

2020-09-09 17:58 UTC, Nitwel commented on app/src/interfaces/code/code.vue
> +			}
🤦 Yea right!

2020-09-10 15:06 UTC, rijkvanzanten requested changes

2020-09-10 15:09 UTC, rijkvanzanten approved these changes

2020-09-10 15:21 UTC, rijkvanzanten approved these changes

2020-09-10 15:21 UTC, merged