Adds a v-field-select component
directus/next pull request #282
Opened 2020-09-11 12:20 UTC by Nitwel

Here is a short preview of how it looks currently.
![GIF 11 09 2020 14-11-46](https://user-images.githubusercontent.com/22577866/92924799-c98d1100-f439-11ea-82b9-2c0bed835a8c.gif)

2020-09-11 12:28 UTC, Nitwel commented
Not to me. Remove that component from the layout when done!

2020-09-11 13:08 UTC, benhaynes commented
Shifting to a tags styling...

![Screen Shot 2020-09-11 at 9 06 41 AM](https://user-images.githubusercontent.com/522079/92929317-5621da00-f40e-11ea-923c-9633dfd0d77f.png)

2020-09-17 18:40 UTC, rijkvanzanten requested changes

2020-09-17 18:40 UTC, rijkvanzanten commented on app/src/components/v-field-select/v-field-select.vue
> +			showArrow
```suggestion
			show-arrow
```

2020-09-17 18:40 UTC, rijkvanzanten commented on app/src/interfaces/many-to-many/options.vue
> +			)?.[0];
It's not a given that the first of the two is always the junction one. We'll have to double check the actual relation to make sure it's the o2m, and not the m2o

2020-09-17 18:40 UTC, rijkvanzanten commented on app/src/interfaces/one-to-many/options.vue
> +			)?.[0];
Same here

2020-09-17 18:40 UTC, rijkvanzanten commented on app/src/interfaces/one-to-many/options.vue
> +			return relationData.many_collection;
With the `?.[0]` above, relationData can be undefined

2020-09-24 18:47 UTC, rijkvanzanten commented on app/src/interfaces/many-to-many/options.vue
> +	<v-notice type="warning" v-if="collection == null">
Another one @Nitwel :P 

```suggestion
	<v-notice type="warning" v-if="collection === null">
```

2020-09-24 20:09 UTC, rijkvanzanten approved these changes

2020-09-24 20:09 UTC, merged