force port to always be evaluated as number
directus/next pull request #380
Opened 2020-09-21 17:54 UTC by kukulaka

when config was generated, port was being parsed as string. MSSQL driver does not like this.

2020-09-21 17:58 UTC, rijkvanzanten requested changes

2020-09-21 17:58 UTC, rijkvanzanten commented on api/src/database/index.ts
> +console.log(connectionConfig);
Sneaky console log!

2020-09-21 17:58 UTC, rijkvanzanten commented on api/src/database/index.ts
> +	}
I'm wondering if we should try this for any key in `/src/env.ts` instead. There's quite a couple "number" configurations (like rate limiter points) that would be convenient to convert ahead of time 🤔

2020-09-21 20:58 UTC, kukulaka commented on api/src/database/index.ts
> +	}
@rijkvanzanten that sounds like a good idea to me 💯

2020-09-24 18:30 UTC, rijkvanzanten commented on api/src/database/index.ts
> +	}
We should do this in `src/env.ts` instead 🙂  (across all env vars)

2020-10-12 16:03 UTC, mscbpi commented on api/src/database/index.ts
> +	}
@rijkvanzanten  may you review https://github.com/directus/next/pull/623 ?

2020-10-12 16:04 UTC, rijkvanzanten commented on api/src/database/index.ts
> +	}
I may! (no need to tag me btw, I see everything coming in/going out of directus/* 😉 )

2020-10-12 16:05 UTC, rijkvanzanten commented
Closed in favor of https://github.com/directus/next/pull/623

2020-10-12 16:05 UTC, closed without merging