Tweak shortcuts
directus/next pull request #415
Opened 2020-09-24 09:43 UTC by Nitwel

closes #235
Shortcuts now allow for multiple handlers on a single event.
Its also allows us to close any modal on `escape` and in the right order!
![GIF 24 09 2020 11-22-02](https://user-images.githubusercontent.com/22577866/94128936-081fc400-fe5b-11ea-8656-8a299dd9507c.gif)

2020-09-24 18:37 UTC, rijkvanzanten requested changes

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/components/v-dialog/v-dialog.vue
> +	<div class="v-dialog" ref="dialog">
I don't think this ref is used

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/components/v-dialog/v-dialog.vue
> +			ref(document.body),
Can we make `ref(document.body)` the default?

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/components/v-table/v-table.vue
> +		);
Lets remove the shortcut from the table, in favor of doing the shortcut in the tabular layout

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/composables/use-shortcut/readme.md
> +		useShortcut('meta+s', save);
This uses a different order (the correct one) than the actual use

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/composables/use-shortcut/use-shortcut.ts
> +			// if the return value is true discontinue going through the queue.
So `return` false at the end of the shortcut _stops_ it from firing the next?

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/composables/use-shortcut/use-shortcut.ts
> +			// if the return value is true discontinue going through the queue.
If yes, lets reverse that to be 

```
function handler() {
  return false;
}
```

to cancel out the next one

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/composables/use-shortcut/use-shortcut.ts
> +	...shortcuts: string[]
Lets make this `useShortcut(shortcut: (string | string[]), handler: ShortcutHandler, reference = ref(document.body))`

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/composables/use-shortcut/use-shortcut.ts
> +		if (reference.value === null) return;
Lets default the reference el to document.body

2020-09-24 18:37 UTC, rijkvanzanten commented on app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
> +		const active = ref(true);
I don't think we have to track `active` in here. We can leave `active` up top (L3) to be `true`, and just add that `@toggle` handler

2020-09-28 17:02 UTC, Nitwel commented on app/src/composables/use-shortcut/use-shortcut.ts
> +		if (reference.value === null) return;
I'll leave that in to make sure that an existing element is passed over.

2020-09-29 22:28 UTC, rijkvanzanten approved these changes

2020-09-29 22:29 UTC, merged