Dynamic OAS generation.
directus/next pull request #452
Opened 2020-09-30 13:53 UTC by Nitwel

Generate a dynamic OAS depending on custom collections and access the specs via `/server/specs/oas`

2020-10-02 16:06 UTC, rijkvanzanten requested changes

2020-10-02 16:22 UTC, Nitwel commented on api/src/services/specifications.ts
> +]
We have to hardcode these because there are some collections that do not have an endpoint.
e.g `sessions`, `migrations` and `field` / `folders` because they get formatted by the api (`meta`, `schema`) and the default way of doing this wouldn't match these two.

We could change it to a blacklist though.

2020-10-02 16:22 UTC, Nitwel commented on api/src/services/specifications.ts
> +    }
💯

2020-10-06 20:30 UTC, rijkvanzanten approved these changes

2020-10-06 20:30 UTC, merged