Fix opening repeater row when creating new one
directus/next pull request #575
Opened 2020-10-07 15:54 UTC by Nitwel

closes #574

2020-10-08 13:45 UTC, rijkvanzanten requested changes

2020-10-08 13:45 UTC, rijkvanzanten commented on app/src/components/v-item-group/v-item.vue
> +		<slot v-bind="{ 'active': isActive, toggle }" />
```suggestion
		<slot v-bind="{ active: isActive, toggle }" />
```

2020-10-08 13:45 UTC, rijkvanzanten commented on app/src/components/v-item-group/v-item.vue
> +		}
What does watch do

2020-10-09 11:50 UTC, Nitwel commented on app/src/components/v-item-group/v-item.vue
> +		}
enables/disables the watcher. If set to false the `active ref<bool>` will not update the state of the item after it got initialized.

2020-10-11 22:55 UTC, rijkvanzanten commented on app/src/components/v-item-group/v-item.vue
> +		}
Could you elaborate on that? I don't know what you mean by 

> If set to false the active ref<bool> will not update the state of the item after it got initialized.

2020-10-14 16:44 UTC, rijkvanzanten approved these changes

2020-10-14 16:44 UTC, merged