Add modified_on to files
directus/next pull request #576
Opened 2020-10-07 16:52 UTC by Nitwel

2020-10-08 13:39 UTC, rijkvanzanten requested changes

2020-10-08 13:39 UTC, rijkvanzanten commented on api/src/database/seeds/01-tables/07-files.yaml
> +    default: '$now'
Doesn't need a default, relies on the date-updated transform

2020-10-08 13:39 UTC, rijkvanzanten commented on api/src/database/seeds/03-fields/05-files.yaml
> +    display: dateTime
Display is called `datetime`, not `dateTime`

2020-10-08 13:39 UTC, rijkvanzanten commented on api/src/database/seeds/01-tables/07-files.yaml
> +      column: id
Note to self: this will cause an issue in a couple days/weeks where somebody tries to delete a user that has previously modified files

2020-10-08 13:39 UTC, rijkvanzanten commented on app/src/modules/files/components/file-info-drawer-detail.vue
> +		const { user_created, user_modified } = useUser();
Use camelCase

2020-10-08 13:39 UTC, rijkvanzanten commented on app/src/modules/files/components/file-info-drawer-detail.vue
> +					if(props.file.modified_on) {
@Nitwel could you run `vue-cli-service lint` before publishing PRs? Seeing a couple strange code formatting quirks that should've been auto-fixed

2020-10-09 11:58 UTC, Nitwel commented on app/src/modules/files/components/file-info-drawer-detail.vue
> +					if(props.file.modified_on) {
I would love to see this being automatic again and I did not disable it, it just stopped working.

2020-10-09 12:03 UTC, Nitwel commented on app/src/modules/files/components/file-info-drawer-detail.vue
> +					if(props.file.modified_on) {
And I can't run vue-cli-service lint either because then my commit would look like this:
![grafik](https://user-images.githubusercontent.com/22577866/95580768-29c2a300-0a38-11eb-80b4-cfd69c6e576e.png)

2020-10-11 22:54 UTC, rijkvanzanten approved these changes

2020-10-11 22:54 UTC, merged