Add singleton option to collection creation
directus/next pull request #586
Opened 2020-10-08 10:23 UTC by Nitwel

closes #336 
Now looks like this:
![grafik](https://user-images.githubusercontent.com/22577866/95446795-15f83d80-0961-11eb-9b8a-e9309c72141d.png)

2020-10-08 14:20 UTC, rijkvanzanten requested changes

2020-10-08 14:20 UTC, rijkvanzanten commented on app/src/modules/docs/routes/static.vue
> +		const view = ref<Vue | null>(null);
Unrelated change from a different PR that has since been merged and altered. Can you remove this change @Nitwel ?

2020-10-09 12:09 UTC, Nitwel commented on app/src/modules/docs/routes/static.vue
> +		const view = ref<Vue | null>(null);
I thought GitHub would update this automaticly when that PR got merged but I had to merge in the main here too to get rid of that.

2020-10-11 22:50 UTC, rijkvanzanten approved these changes

2020-10-11 22:50 UTC, merged