Add user invitation
directus/next pull request #731
Opened 2020-10-20 10:49 UTC by Nitwel

closes #119 
![grafik](https://user-images.githubusercontent.com/22577866/96576542-9c523f00-12d2-11eb-9f89-3db44bdc69e5.png)
![grafik](https://user-images.githubusercontent.com/22577866/96576581-ad9b4b80-12d2-11eb-8936-8637fb139c44.png)

2020-10-20 13:53 UTC, benhaynes commented
Perfect!! Thank you Nils...

Two questions:
* Let's ensure the proper label/field spacing is there... I think it's 8px, but we should confirm.
* Should this be a textarea instead of an input? Might make sense for longer CSVs

2020-10-20 13:58 UTC, Nitwel commented
It is using the tags interface. So the button only gets clickable when you added a tag containing an email.
The default spacing for that is 4px as far as I know but I can look into that.

2020-10-20 14:01 UTC, benhaynes commented
Confirmed that it's 8px (see below). Ahh, tags interface works!

![Screen Shot 2020-10-20 at 10 00 58 AM](https://user-images.githubusercontent.com/522079/96596928-3efec380-12bb-11eb-9038-9945a6e59317.png)

2020-10-20 14:02 UTC, Nitwel commented
The `type-label` was a span and not a div. That's why it ignored that margin.

2020-10-20 14:58 UTC, rijkvanzanten requested changes

2020-10-20 14:58 UTC, rijkvanzanten commented on app/src/views/private/components/users-invite/users-invite.vue
> +					></interface-tags>
```suggestion
					/>
```

2020-10-20 14:58 UTC, rijkvanzanten commented on app/src/views/private/components/users-invite/users-invite.vue
> +					<v-select v-model="roleSelected" :items="roles"></v-select>
```suggestion
					<v-select v-model="roleSelected" :items="roles" />
```

2020-10-20 19:10 UTC, Nitwel commented on app/src/views/private/components/users-invite/users-invite.vue
> +			const response = await api.get('/roles');
How would I check for that?

2020-10-21 17:28 UTC, rijkvanzanten approved these changes

2020-10-21 17:28 UTC, merged