Updating CORS_ENABLED to true by default
directus/next pull request #872
Opened 2020-11-04 02:01 UTC by juancarlosjr97

Updating CORS_ENABLED to true by default as the documentation describes

2020-11-04 08:17 UTC, maartenvn commented
You defaulted `CACHE_ENABLED` to true instead of `CORS_ENABLED`

2020-11-04 08:17 UTC, maartenvn requested changes

2020-11-04 08:17 UTC, maartenvn commented on api/src/env.ts
> +	CACHE_ENABLED: true,
You meant to change `CORS_ENABLED` but you changed `CACHE_ENABLED` right?

2020-11-04 08:27 UTC, juancarlosjr97 commented on api/src/env.ts
> +	CACHE_ENABLED: true,
Yes, tails of making a mistake half-asleep.... Thank you @maartenvn

2020-11-04 14:52 UTC, rijkvanzanten approved these changes

2020-11-04 14:52 UTC, merged

2020-11-05 21:15 UTC, rijkvanzanten commented
@fatihky that was resolved a commit later, see https://github.com/directus/next/pull/872/files for the final changes in this PR

2020-11-06 06:48 UTC, fatihky commented
@rijkvanzanten sorry, I see. thank you for the information. I was just looking at individual commits so I missed that.